server.port=8081

# 1. MongoDB Connection (Password @ is URL-encoded as %40)
spring.data.mongodb.uri=mongodb+srv://ishan:ishan%401234@cluster4.n226at2.mongodb.net/SmartCampusDB?appName=Cluster4

# Encryption Key
app.encryption.key=SmartCampusKey12

# JWT Secret & Expiration
jwt.secret=4r685b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6
jwt.expiration=86400000
